/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Course;
import controller.CourseController;
import javax.swing.JOptionPane;

public class CourseForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourseForm.class.getName());
    
    private String selectedKode;
    CourseController controller = new CourseController(); 
    
    final String[] sksList     = {"2", "3", "4"};
    final String[] semesterList = {"1", "2", "3", "4", "5", "6", "7", "8"};
    
    public CourseForm() {
        initComponents();
        loadCourseData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void loadCourseData() {
        List<Course> courses = controller.getCourse();
        String[][] data = new String[courses.size()][4];
 
        for (int i = 0; i < courses.size(); i++) {
            data[i][0] = courses.get(i).getCourseName();
            data[i][1] = courses.get(i).getCode();
            data[i][2] = String.valueOf(courses.get(i).getSKS());      
            data[i][3] = String.valueOf(courses.get(i).getSemester());
        }
 
        String[] columnNames = {"Nama", "Kode", "SKS", "Semester"};
        jTableMatkul.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMatkul = new javax.swing.JTable();
        jButtonSearch = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxSKS = new javax.swing.JComboBox<>();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldKode = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxSemester = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDashbord = new javax.swing.JMenu();
        jMenuStudent = new javax.swing.JMenu();
        jMenuLecture = new javax.swing.JMenu();
        jMenuKRS = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("FORM MATA KULIAH");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabel Mata Kuliah", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 13))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("Search : ");

        jTableMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMatkulMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMatkul);

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(this::jButtonSearchActionPerformed);

        jButton2.setText(">>");

        jButton3.setText("<<");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton1.setText("Reset");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSearch)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Kode");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("SKS");

        jComboBoxSKS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        jComboBoxSKS.addActionListener(this::jComboBoxSKSActionPerformed);

        jButtonDelete.setForeground(new java.awt.Color(255, 0, 51));
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(this::jButtonSimpanActionPerformed);

        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(this::jButtonBatalActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("Semester");

        jComboBoxSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxSKS, 0, 131, Short.MAX_VALUE)
                            .addComponent(jTextFieldKode)
                            .addComponent(jTextFieldNama)
                            .addComponent(jComboBoxSemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBatal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButtonDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSimpan)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonSimpan))
                .addGap(30, 30, 30)
                .addComponent(jButtonBatal)
                .addContainerGap())
        );

        jMenuDashbord.setText("Dashbord");
        jMenuDashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDashbordMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuDashbord);

        jMenuStudent.setText("AddStudent");
        jMenuStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuStudentMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuStudent);

        jMenuLecture.setText("AddLecture");
        jMenuLecture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLectureMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLecture);

        jMenuKRS.setText("AddKRS");
        jMenuKRS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuKRSMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuKRS);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearForm() {
        jTextFieldNama.setText("");
        jTextFieldKode.setText("");
        jComboBoxSKS.setSelectedIndex(0);
        jComboBoxSemester.setSelectedIndex(0);
        jTextFieldKode.setEditable(true);
        selectedKode = null;
    }
    
    private void jTableMatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMatkulMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTableMatkul.getSelectedRow();
        if (selectedRow != -1) {
            jTextFieldNama.setText(jTableMatkul.getValueAt(selectedRow, 0).toString());
            jTextFieldKode.setText(jTableMatkul.getValueAt(selectedRow, 1).toString());
            jTextFieldKode.setEditable(false);
            selectedKode = jTableMatkul.getValueAt(selectedRow, 1).toString();

            String sksVal = jTableMatkul.getValueAt(selectedRow, 2).toString();
            jComboBoxSKS.setSelectedItem(sksVal);

            String semVal = jTableMatkul.getValueAt(selectedRow, 3).toString();
            jComboBoxSemester.setSelectedItem(semVal);
        }
    }//GEN-LAST:event_jTableMatkulMouseClicked

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String keyword = jTextFieldSearch.getText().toLowerCase();
        List<Course> all = controller.getCourse();
        List<Course> filtered = new java.util.ArrayList<>();
    
        for (Course l : all) {
            if (l.getCourseName().toLowerCase().contains(keyword) ||
                l.getCode().toLowerCase().contains(keyword) ||
                l.getSKSString().toLowerCase().contains(keyword) ||
                l.getSemesterString().toLowerCase().contains(keyword)) {  // ← tambahkan ini
                filtered.add(l);
                }
        }
    
        String[][] data = new String[filtered.size()][4];
        for (int i = 0; i < filtered.size(); i++) {
            data[i][0] = filtered.get(i).getCode();
            data[i][1] = filtered.get(i).getCourseName();
            data[i][2] = filtered.get(i).getSKSString();
            data[i][3] = filtered.get(i).getSemesterString();
            }
        String[] cols = {"Kode", "Nama", "SKS", "Semester"};
        jTableMatkul.setModel(new javax.swing.table.DefaultTableModel(data, cols));
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this Course?",
            "Delete Confirmation",
            JOptionPane.YES_NO_OPTION
        );

        if(confirm == JOptionPane.YES_OPTION) {
            // Proses delete
            try {
                controller.delete(selectedKode);
                JOptionPane.showMessageDialog(this,"Course deleted successfully!");
                this.selectedKode=null;
                this.clearForm();
                loadCourseData();
            } catch (Exception ex) {
                Logger.getLogger(StudentForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,"deleted unsuccessfully!");
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        String nama = jTextFieldNama.getText();
        String kode = jTextFieldKode.getText();
        String strSKS = jComboBoxSKS.getSelectedItem().toString();
        String strSemester = jComboBoxSemester.getSelectedItem().toString();

        if(nama.isEmpty() || kode.isEmpty() || strSKS.isEmpty() || strSemester.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all fields ", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
        else {

            int SKS = Integer.parseInt(strSKS);
            int semester = Integer.parseInt(strSemester);
            Course course = new Course(kode, nama, SKS, semester);
            try {

                int res;
                if(selectedKode != null){

                    res = controller.update(course, selectedKode);
                }
                else{
                    res = controller.create(course);
                }
                if (res == 1) {
                    JOptionPane.showMessageDialog(this, "Data created successfully ", "Success", JOptionPane.INFORMATION_MESSAGE);
                    this.selectedKode=null;
                    this.clearForm();
                    loadCourseData();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Error occurred while inserting ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed

        clearForm();
        
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jComboBoxSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSKSActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSKSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextFieldSearch.setText("");
        loadCourseData();
        clearForm();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuDashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDashbordMouseClicked
        // TODO add your handling code here:
        Dashbord dashbord = null;
        dashbord = new Dashbord();
        dashbord.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuDashbordMouseClicked

    private void jMenuStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuStudentMouseClicked
        // TODO add your handling code here:
        StudentForm studentForm = null;
        try {
            studentForm = new StudentForm();
        } catch (SQLException ex) {
            System.getLogger(CourseForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        studentForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuStudentMouseClicked

    private void jMenuLectureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLectureMouseClicked
        // TODO add your handling code here:
        LectureForm lectureForm = null;
        try {
            lectureForm = new LectureForm();
        } catch (SQLException ex) {
            System.getLogger(CourseForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        lectureForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuLectureMouseClicked

    private void jMenuKRSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuKRSMouseClicked
        // TODO add your handling code here:
        KRSForm krsForm = null;
        krsForm = new KRSForm();
        krsForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuKRSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new CourseForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox<String> jComboBoxSKS;
    private javax.swing.JComboBox<String> jComboBoxSemester;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDashbord;
    private javax.swing.JMenu jMenuKRS;
    private javax.swing.JMenu jMenuLecture;
    private javax.swing.JMenu jMenuStudent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMatkul;
    private javax.swing.JTextField jTextFieldKode;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
